#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

DIRECTORY=/app/node_modules

if [ ! -d "$DIRECTORY" ]; then
    npm install
fi

python manage.py migrate
exec python manage.py runserver_plus 0.0.0.0:8000
