version: '3'

volumes:
  walletapp_local_postgres_data: {}
  walletapp_local_postgres_data_backups: {}


services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./compose/local/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: walletapp_local_django
    container_name: walletapp_local_django
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: walletapp_production_postgres
    container_name: walletapp_local_postgres
    volumes:
      - walletapp_local_postgres_data:/var/lib/postgresql/data:Z
      - walletapp_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: walletapp_local_docs
    container_name: walletapp_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./walletapp:/app/walletapp:z
    ports:
      - "9000:9000"
    command: /start-docs

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: walletapp_local_mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: walletapp_local_redis

  celeryworker:
    <<: *django
    image: walletapp_local_celeryworker
    container_name: walletapp_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: walletapp_local_celerybeat
    container_name: walletapp_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: walletapp_local_flower
    container_name: walletapp_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
