# Generated by Django 4.1.4 on 2022-12-21 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incomes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="income",
            name="slug",
        ),
    ]
