# Generated by Django 4.1.3 on 2022-12-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="credit",
            name="status",
            field=models.CharField(
                choices=[("paid", "paid"), ("active", "active")],
                default="active",
                max_length=6,
                verbose_name="status",
            ),
        ),
    ]
